// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DotsAndBoxesImage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DotsAndBoxesImage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace AlphaDots {
class DotsAndBoxesImageDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DotsAndBoxesImage>
     _instance;
} _DotsAndBoxesImage_default_instance_;

namespace protobuf_DotsAndBoxesImage_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DotsAndBoxesImage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DotsAndBoxesImage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DotsAndBoxesImage, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DotsAndBoxesImage, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DotsAndBoxesImage, pixels_),
  0,
  1,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(DotsAndBoxesImage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_DotsAndBoxesImage_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "DotsAndBoxesImage.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _DotsAndBoxesImage_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_DotsAndBoxesImage_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027DotsAndBoxesImage.proto\022\tAlphaDots\"B\n\021"
      "DotsAndBoxesImage\022\r\n\005width\030\001 \002(\005\022\016\n\006heig"
      "ht\030\002 \002(\005\022\016\n\006pixels\030\003 \003(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 104);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DotsAndBoxesImage.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_DotsAndBoxesImage_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DotsAndBoxesImage::kWidthFieldNumber;
const int DotsAndBoxesImage::kHeightFieldNumber;
const int DotsAndBoxesImage::kPixelsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DotsAndBoxesImage::DotsAndBoxesImage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_DotsAndBoxesImage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:AlphaDots.DotsAndBoxesImage)
}
DotsAndBoxesImage::DotsAndBoxesImage(const DotsAndBoxesImage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      pixels_(from.pixels_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&width_, &from.width_,
    static_cast<size_t>(reinterpret_cast<char*>(&height_) -
    reinterpret_cast<char*>(&width_)) + sizeof(height_));
  // @@protoc_insertion_point(copy_constructor:AlphaDots.DotsAndBoxesImage)
}

void DotsAndBoxesImage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&width_)) + sizeof(height_));
}

DotsAndBoxesImage::~DotsAndBoxesImage() {
  // @@protoc_insertion_point(destructor:AlphaDots.DotsAndBoxesImage)
  SharedDtor();
}

void DotsAndBoxesImage::SharedDtor() {
}

void DotsAndBoxesImage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DotsAndBoxesImage::descriptor() {
  protobuf_DotsAndBoxesImage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_DotsAndBoxesImage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DotsAndBoxesImage& DotsAndBoxesImage::default_instance() {
  protobuf_DotsAndBoxesImage_2eproto::InitDefaults();
  return *internal_default_instance();
}

DotsAndBoxesImage* DotsAndBoxesImage::New(::google::protobuf::Arena* arena) const {
  DotsAndBoxesImage* n = new DotsAndBoxesImage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DotsAndBoxesImage::Clear() {
// @@protoc_insertion_point(message_clear_start:AlphaDots.DotsAndBoxesImage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pixels_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&width_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&height_) -
        reinterpret_cast<char*>(&width_)) + sizeof(height_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DotsAndBoxesImage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AlphaDots.DotsAndBoxesImage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 width = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 height = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_height();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 pixels = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24u, input, this->mutable_pixels())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_pixels())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AlphaDots.DotsAndBoxesImage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AlphaDots.DotsAndBoxesImage)
  return false;
#undef DO_
}

void DotsAndBoxesImage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AlphaDots.DotsAndBoxesImage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 width = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->width(), output);
  }

  // required int32 height = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->height(), output);
  }

  // repeated int32 pixels = 3;
  for (int i = 0, n = this->pixels_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->pixels(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AlphaDots.DotsAndBoxesImage)
}

::google::protobuf::uint8* DotsAndBoxesImage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:AlphaDots.DotsAndBoxesImage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 width = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->width(), target);
  }

  // required int32 height = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->height(), target);
  }

  // repeated int32 pixels = 3;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteInt32ToArray(3, this->pixels_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AlphaDots.DotsAndBoxesImage)
  return target;
}

size_t DotsAndBoxesImage::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:AlphaDots.DotsAndBoxesImage)
  size_t total_size = 0;

  if (has_width()) {
    // required int32 width = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  if (has_height()) {
    // required int32 height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  return total_size;
}
size_t DotsAndBoxesImage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AlphaDots.DotsAndBoxesImage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 width = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());

    // required int32 height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated int32 pixels = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->pixels_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->pixels_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DotsAndBoxesImage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AlphaDots.DotsAndBoxesImage)
  GOOGLE_DCHECK_NE(&from, this);
  const DotsAndBoxesImage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DotsAndBoxesImage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AlphaDots.DotsAndBoxesImage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AlphaDots.DotsAndBoxesImage)
    MergeFrom(*source);
  }
}

void DotsAndBoxesImage::MergeFrom(const DotsAndBoxesImage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AlphaDots.DotsAndBoxesImage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  pixels_.MergeFrom(from.pixels_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      width_ = from.width_;
    }
    if (cached_has_bits & 0x00000002u) {
      height_ = from.height_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void DotsAndBoxesImage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AlphaDots.DotsAndBoxesImage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DotsAndBoxesImage::CopyFrom(const DotsAndBoxesImage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AlphaDots.DotsAndBoxesImage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DotsAndBoxesImage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void DotsAndBoxesImage::Swap(DotsAndBoxesImage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DotsAndBoxesImage::InternalSwap(DotsAndBoxesImage* other) {
  using std::swap;
  pixels_.InternalSwap(&other->pixels_);
  swap(width_, other->width_);
  swap(height_, other->height_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DotsAndBoxesImage::GetMetadata() const {
  protobuf_DotsAndBoxesImage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_DotsAndBoxesImage_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DotsAndBoxesImage

// required int32 width = 1;
bool DotsAndBoxesImage::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void DotsAndBoxesImage::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
void DotsAndBoxesImage::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
void DotsAndBoxesImage::clear_width() {
  width_ = 0;
  clear_has_width();
}
::google::protobuf::int32 DotsAndBoxesImage::width() const {
  // @@protoc_insertion_point(field_get:AlphaDots.DotsAndBoxesImage.width)
  return width_;
}
void DotsAndBoxesImage::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:AlphaDots.DotsAndBoxesImage.width)
}

// required int32 height = 2;
bool DotsAndBoxesImage::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void DotsAndBoxesImage::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
void DotsAndBoxesImage::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
void DotsAndBoxesImage::clear_height() {
  height_ = 0;
  clear_has_height();
}
::google::protobuf::int32 DotsAndBoxesImage::height() const {
  // @@protoc_insertion_point(field_get:AlphaDots.DotsAndBoxesImage.height)
  return height_;
}
void DotsAndBoxesImage::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:AlphaDots.DotsAndBoxesImage.height)
}

// repeated int32 pixels = 3;
int DotsAndBoxesImage::pixels_size() const {
  return pixels_.size();
}
void DotsAndBoxesImage::clear_pixels() {
  pixels_.Clear();
}
::google::protobuf::int32 DotsAndBoxesImage::pixels(int index) const {
  // @@protoc_insertion_point(field_get:AlphaDots.DotsAndBoxesImage.pixels)
  return pixels_.Get(index);
}
void DotsAndBoxesImage::set_pixels(int index, ::google::protobuf::int32 value) {
  pixels_.Set(index, value);
  // @@protoc_insertion_point(field_set:AlphaDots.DotsAndBoxesImage.pixels)
}
void DotsAndBoxesImage::add_pixels(::google::protobuf::int32 value) {
  pixels_.Add(value);
  // @@protoc_insertion_point(field_add:AlphaDots.DotsAndBoxesImage.pixels)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DotsAndBoxesImage::pixels() const {
  // @@protoc_insertion_point(field_list:AlphaDots.DotsAndBoxesImage.pixels)
  return pixels_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DotsAndBoxesImage::mutable_pixels() {
  // @@protoc_insertion_point(field_mutable_list:AlphaDots.DotsAndBoxesImage.pixels)
  return &pixels_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace AlphaDots

// @@protoc_insertion_point(global_scope)
